 .env.production.example                  |  105 [32m+[m
 .github/workflows/node.js.yml            |   31 [32m+[m
 .github/workflows/npm-publish.yml        |   33 [32m+[m
 .gitignore                               |    3 [32m+[m
 .vercelignore                            |   27 [32m+[m
 CALLFLOW.md                              |  126 [32m++[m
 CHATGPT_CONNECTOR_SETUP.md               |  151 [32m++[m
 CONFIGURACION_VSCODE_CLAUDE.md           |   39 [32m+[m
 DEPLOYMENT_COMPLETO.md                   |  121 [32m++[m
 DEPLOY_CHECKLIST.md                      |  231 [32m+++[m
 DEPLOY_FINAL.md                          |  148 [32m++[m
 DEPLOY_FINAL_AUTO.md                     |   66 [32m+[m
 DEPLOY_NOW.md                            |  127 [32m++[m
 DEPLOY_PRODUCCION.md                     |  361 [32m++++[m
 DEPLOY_STATUS.md                         |   66 [32m+[m
 DEPLOY_STEPS.md                          |  110 [32m++[m
 ENV_UTILS_GUIDE.md                       |  329 [32m++++[m
 ENV_VARIABLES_GUIDE.md                   |  165 [32m++[m
 ENV_VARS_COMPLETE.md                     |  186 [32m++[m
 FLUJO_COMPLETO_VOZ_SANDRA.md             |  266 [32m+++[m
 MCP_COMPLETO.md                          |  166 [32m++[m
 MCP_DEPLOYMENT_GUIDE.md                  |  299 [32m+++[m
 MCP_IMPLEMENTATION_SUMMARY.md            |  258 [32m+++[m
 MCP_RESUMEN_FINAL.md                     |  206 [32m++[m
 NGROK_QUICK_SETUP.md                     |   89 [32m+[m
 NGROK_SETUP.md                           |  263 [32m+++[m
 ONBOARDING_TECNICO.md                    |  472 [32m+++++[m
 POST_PRODUCTION_READY.md                 |  184 [32m++[m
 PRE_DEPLOY_VERIFY.js                     |  170 [32m++[m
 PRODUCTION_URL.txt                       |   15 [32m+[m
 QUICK_START.md                           |  312 [32m+++[m
 README.md                                |  111 [32m++[m
 README_VERCEL.md                         |   69 [32m+[m
 SETUP_ENV.md                             |   94 [32m+[m
 STATUS_MCP.md                            |   56 [32m+[m
 TEST_MCP_MANUAL.md                       |  253 [32m+++[m
 TEST_MCP_SERVER.ps1                      |  104 [32m+[m
 TEST_NGROK.ps1                           |  121 [32m++[m
 USAGE_EXAMPLES.md                        |  611 [32m++++++[m
 VERCEL_DEPLOY.md                         |  107 [32m++[m
 WIDGET_PRODUCTION_CHECKLIST.md           |  127 [32m++[m
 WIDGET_WORKFLOW.md                       |  184 [32m++[m
 WORKFLOW_MCP_SANDRA.md                   |  290 [32m+++[m
 add-bridgedata-final.js                  |  132 [32m++[m
 add-bridgedata-key.md                    |   53 [32m+[m
 add-missing-env-vars.js                  |  307 [32m+++[m
 api/sandra/chat.js                       |  321 [32m++++[m
 api/sandra/mcp-proxy.js                  |   83 [32m+[m
 api/sandra/transcribe.js                 |   97 [32m+[m
 api/sandra/voice.js                      |   90 [32m+[m
 assets/js/sandra-widget.js               |  720 [32m+++++++[m
 bastanteo-mcp-design.json                |  309 [32m+++[m
 config-claude-vscode.ps1                 |   32 [32m+[m
 configure-vercel-env.js                  |  215 [32m+++[m
 deploy-complete.ps1                      |  165 [32m++[m
 deploy-vercel.js                         |  292 [32m+++[m
 deploy-with-tokens.js                    |  212 [32m+++[m
 fix-claude-api.ps1                       |   22 [32m+[m
 get-ngrok-url.ps1                        |   37 [32m+[m
 get-vercel-info.js                       |  107 [32m++[m
 index.html                               |  900 [32m++++++++[m[31m-[m
 index.html.backup                        | 3057 [32m++++++++++++++++++++++++++++++[m
 mcp-server/.dockerignore                 |   12 [32m+[m
 mcp-server/.env.production.example       |   44 [32m+[m
 mcp-server/.gitignore                    |   16 [32m+[m
 mcp-server/DEPLOY_AND_TEST.md            |  194 [32m++[m
 mcp-server/DEPLOY_PRODUCCION.md          |  326 [32m++++[m
 mcp-server/Dockerfile                    |   38 [32m+[m
 mcp-server/README.md                     |  147 [32m++[m
 mcp-server/README_ENV_PRODUCTION.md      |  272 [32m+++[m
 mcp-server/TEST_RESULTS_FINAL.md         |  130 [32m++[m
 mcp-server/TEST_RESULTS_SUMMARY.md       |  112 [32m++[m
 mcp-server/config/mcp.config.json        |   75 [32m+[m
 mcp-server/configure-production-vars.ps1 |   23 [32m+[m
 mcp-server/docker-compose.yml            |   24 [32m+[m
 mcp-server/index.js                      |  343 [32m++++[m
 mcp-server/middleware/auth.js            |   30 [32m+[m
 mcp-server/middleware/errorHandler.js    |   20 [32m+[m
 mcp-server/package-lock.json             | 1245 [32m++++++++++++[m
 mcp-server/package.json                  |   34 [32m+[m
 mcp-server/router/mcp-router.js          |  132 [32m++[m
 mcp-server/routes/apis.js                |   94 [32m+[m
 mcp-server/routes/audio.js               |   85 [32m+[m
 mcp-server/routes/conserje.js            |  109 [32m++[m
 mcp-server/routes/sync.js                |   50 [32m+[m
 mcp-server/routes/video.js               |   69 [32m+[m
 mcp-server/scripts/setup-public-apis.js  |   62 [32m+[m
 mcp-server/server.js                     |  143 [32m++[m
 mcp-server/services/ambientation.js      |  107 [32m++[m
 mcp-server/services/bridgeData.js        |   83 [32m+[m
 mcp-server/services/cartesia.js          |   98 [32m+[m
 mcp-server/services/chat.js              |  178 [32m++[m
 mcp-server/services/commands.js          |  127 [32m++[m
 mcp-server/services/publicAPIs.js        |   71 [32m+[m
 mcp-server/services/qwen.js              |  174 [32m++[m
 mcp-server/services/scheduler.js         |  137 [32m++[m
 mcp-server/services/snapshot.js          |  167 [32m++[m
 mcp-server/services/transcriber.js       |   99 [32m+[m
 mcp-server/services/videoSync.js         |   60 [32m+[m
 mcp-server/services/vision.js            |  159 [32m++[m
 mcp-server/services/voice.js             |  141 [32m++[m
 mcp-server/start-and-test.ps1            |   70 [32m+[m
 mcp-server/test-mcp-complete.js          |  271 [32m+++[m
 mcp-server/utils/public-apis-indexer.js  |   87 [32m+[m
 package.json                             |    7 [32m+[m[31m-[m
 server-mcp.js                            |  631 [32m++++++[m
 server-websocket.js                      |   30 [32m+[m[31m-[m
 setup-pwa-env.js                         |  204 [32m++[m
 src/utils/env.js                         |  605 [32m++++++[m
 start-ngrok.ps1                          |   32 [32m+[m
 start-servers.bat                        |   10 [32m+[m
 vercel.json                              |   16 [32m+[m
 verify-widget-production.js              |  117 [32m++[m
 113 files changed, 21821 insertions(+), 92 deletions(-)
